# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr1.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_axi_dma_0_0/top_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_dma_0_0 || ORIG_REF_NAME==top_axi_dma_0_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_0/top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_us_0/top_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_us_0 || ORIG_REF_NAME==top_auto_us_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_mem_intercon_0/top_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_mem_intercon_0 || ORIG_REF_NAME==top_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_register_0_0/top_axi_register_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_register_0_0 || ORIG_REF_NAME==top_axi_register_0_0} -quiet] -quiet

# IP: bd/top/ip/top_blk_mem_gen_0_0/top_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_blk_mem_gen_0_0 || ORIG_REF_NAME==top_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/top/ip/top_fake_data_src_0_0/top_fake_data_src_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_fake_data_src_0_0 || ORIG_REF_NAME==top_fake_data_src_0_0} -quiet] -quiet

# IP: bd/top/ip/top_fft_config_0_0/top_fft_config_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_fft_config_0_0 || ORIG_REF_NAME==top_fft_config_0_0} -quiet] -quiet

# IP: bd/top/ip/top_fft_tdata_slice_0_0/top_fft_tdata_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_fft_tdata_slice_0_0 || ORIG_REF_NAME==top_fft_tdata_slice_0_0} -quiet] -quiet

# IP: bd/top/ip/top_fifo_generator_0_0/top_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_fifo_generator_0_0 || ORIG_REF_NAME==top_fifo_generator_0_0} -quiet] -quiet

# IP: bd/top/ip/top_fifo_generator_1_0/top_fifo_generator_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_fifo_generator_1_0 || ORIG_REF_NAME==top_fifo_generator_1_0} -quiet] -quiet

# IP: bd/top/ip/top_ila_0_0/top_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_0_0 || ORIG_REF_NAME==top_ila_0_0} -quiet] -quiet

# IP: bd/top/ip/top_ila_1_0/top_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_1_0 || ORIG_REF_NAME==top_ila_1_0} -quiet] -quiet

# IP: bd/top/ip/top_ila_2_0/top_ila_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_2_0 || ORIG_REF_NAME==top_ila_2_0} -quiet] -quiet

# IP: bd/top/ip/top_ila_3_0/top_ila_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_3_0 || ORIG_REF_NAME==top_ila_3_0} -quiet] -quiet

# IP: bd/top/ip/top_ila_4_0/top_ila_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_4_0 || ORIG_REF_NAME==top_ila_4_0} -quiet] -quiet

# IP: bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/top_mipi_csi2_rx_subsyst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mipi_csi2_rx_subsyst_0_0 || ORIG_REF_NAME==top_mipi_csi2_rx_subsyst_0_0} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xbar_0/top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xbar_0 || ORIG_REF_NAME==top_xbar_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_4/top_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_4 || ORIG_REF_NAME==top_auto_pc_4} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_1/top_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_1 || ORIG_REF_NAME==top_auto_pc_1} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_2/top_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_2 || ORIG_REF_NAME==top_auto_pc_2} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_3/top_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_3 || ORIG_REF_NAME==top_auto_pc_3} -quiet] -quiet

# IP: bd/top/ip/top_ps7_0_axi_periph_1/top_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ps7_0_axi_periph_1 || ORIG_REF_NAME==top_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_ps7_0_50M_0 || ORIG_REF_NAME==top_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/top/ip/top_util_vector_logic_0_0/top_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_vector_logic_0_0 || ORIG_REF_NAME==top_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/top/ip/top_util_vector_logic_1_0/top_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_vector_logic_1_0 || ORIG_REF_NAME==top_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/top/ip/top_util_vector_logic_2_0/top_util_vector_logic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_vector_logic_2_0 || ORIG_REF_NAME==top_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/top/ip/top_util_vector_logic_3_0/top_util_vector_logic_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_vector_logic_3_0 || ORIG_REF_NAME==top_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/top/ip/top_xfft_1_0/top_xfft_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xfft_1_0 || ORIG_REF_NAME==top_xfft_1_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconcat_0_0/top_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconcat_0_0 || ORIG_REF_NAME==top_xlconcat_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconcat_1_0/top_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconcat_1_0 || ORIG_REF_NAME==top_xlconcat_1_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_0_0/top_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_0_0 || ORIG_REF_NAME==top_xlconstant_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_0_1/top_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_0_1 || ORIG_REF_NAME==top_xlconstant_0_1} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_1_0/top_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_1_0 || ORIG_REF_NAME==top_xlconstant_1_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_2_0/top_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_2_0 || ORIG_REF_NAME==top_xlconstant_2_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_3_0/top_xlconstant_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_3_0 || ORIG_REF_NAME==top_xlconstant_3_0} -quiet] -quiet

# IP: bd/top/ip/top_xlslice_0_0/top_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlslice_0_0 || ORIG_REF_NAME==top_xlslice_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlslice_1_0/top_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlslice_1_0 || ORIG_REF_NAME==top_xlslice_1_0} -quiet] -quiet

# IP: bd/top/ip/top_xlslice_2_0/top_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlslice_2_0 || ORIG_REF_NAME==top_xlslice_2_0} -quiet] -quiet

# IP: bd/top/ip/top_xlslice_4_0/top_xlslice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlslice_4_0 || ORIG_REF_NAME==top_xlslice_4_0} -quiet] -quiet

# IP: bd/top/ip/top_xlslice_5_0/top_xlslice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlslice_5_0 || ORIG_REF_NAME==top_xlslice_5_0} -quiet] -quiet

# IP: bd/top/ip/top_tlast_gen_0_0/top_tlast_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_tlast_gen_0_0 || ORIG_REF_NAME==top_tlast_gen_0_0} -quiet] -quiet

# IP: bd/top/ip/top_output_mux_0_0/top_output_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_output_mux_0_0 || ORIG_REF_NAME==top_output_mux_0_0} -quiet] -quiet

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: bd/top/ip/top_ila_5_0/top_ila_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_5_0 || ORIG_REF_NAME==top_ila_5_0} -quiet] -quiet

# IP: bd/top/ip/top_SampleControl_0_0/top_SampleControl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_SampleControl_0_0 || ORIG_REF_NAME==top_SampleControl_0_0} -quiet] -quiet

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/top_ooc.xdc
