# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGA/NanoVTX/NanoVTX.srcs/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/top_mipi_csi2_rx_subsyst_0_0.xci
# IP: The module: 'top_mipi_csi2_rx_subsyst_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/bd_0/bd_882f.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882f || ORIG_REF_NAME==bd_882f} -quiet] -quiet

# IP: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_882f_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882f_xbar_0 || ORIG_REF_NAME==bd_882f_xbar_0} -quiet] -quiet

# IP: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_882f_r_sync_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882f_r_sync_0 || ORIG_REF_NAME==bd_882f_r_sync_0} -quiet] -quiet

# IP: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_882f_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882f_rx_0 || ORIG_REF_NAME==bd_882f_rx_0} -quiet] -quiet

# IP: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_882f_phy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882f_phy_0 || ORIG_REF_NAME==bd_882f_phy_0} -quiet] -quiet

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/bd_0/bd_882f_ooc.xdc

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/top_mipi_csi2_rx_subsyst_0_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/top_mipi_csi2_rx_subsyst_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/top_mipi_csi2_rx_subsyst_0_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/FPGA/NanoVTX/NanoVTX.srcs/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/top_mipi_csi2_rx_subsyst_0_0.xci
# IP: The module: 'top_mipi_csi2_rx_subsyst_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/bd_0/bd_882f.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882f || ORIG_REF_NAME==bd_882f} -quiet] -quiet

# IP: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_882f_xbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882f_xbar_0 || ORIG_REF_NAME==bd_882f_xbar_0} -quiet] -quiet

# IP: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_882f_r_sync_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882f_r_sync_0 || ORIG_REF_NAME==bd_882f_r_sync_0} -quiet] -quiet

# IP: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_882f_rx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882f_rx_0 || ORIG_REF_NAME==bd_882f_rx_0} -quiet] -quiet

# IP: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_882f_phy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_882f_phy_0 || ORIG_REF_NAME==bd_882f_phy_0} -quiet] -quiet

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/bd_0/bd_882f_ooc.xdc

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/top_mipi_csi2_rx_subsyst_0_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/top_mipi_csi2_rx_subsyst_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_mipi_csi2_rx_subsyst_0_0/top_mipi_csi2_rx_subsyst_0_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
