# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGA/NanoVTX/NanoVTX.srcs/sources_1/bd/top/ip/top_ila_4_0/top_ila_4_0.xci
# IP: The module: 'top_ila_4_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_ila_4_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_4_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_ila_4_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_ila_4_0/top_ila_4_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/FPGA/NanoVTX/NanoVTX.srcs/sources_1/bd/top/ip/top_ila_4_0/top_ila_4_0.xci
# IP: The module: 'top_ila_4_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_ila_4_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_ila_4_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/NanoVTX/NanoVTX.gen/sources_1/bd/top/ip/top_ila_4_0/top_ila_4_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_4_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
